### ISSUE TITLE
Device missing of device_id can be provisioned as usual

### ISSUE THREAD

**Issue by manfredipist** [telefonicaid/iotagent-node-lib#1298]
### Description:

Device missing of device_id can be provisioned as usual

### Steps to reproduce:

Provision a device using the iotagent-node-lib API "POST @ host:4041/iot/devices"
 
```
{
    "devices": [
        {
            "device_id": "",
            "entity_name": "urn:ngsi-ld:Device:age01_Car",
            "entity_type": "Device",
            "attributes": [
                {
                    "object_id": "ns=3;s=EngineBrake",
                    "name": "EngineBrake",
                    "type": "Number"
                }
             ],
             "lazy": [],
            "commands": [],
            "static_attributes": []
        }
    ]
}
```

### Expected Output:

`{"name":"MISSING_ATTRIBUTES","message":"The request was not well formed:Missing attributes: [\"device_id\"]"}
`
### Actual Output: 

`201 Created`

### Devices GET Output:

```
{
    "count": 1,
    "devices": [
        {
            "device_id": "",
            "service": "openiot5",
            "service_path": "/demo",
            "entity_name": "urn:ngsi-ld:Device:age09_Car",
            "entity_type": "Device",
            "attributes": [
                {
                    "object_id": "ns=3;s=EngineBrake",
                    "name": "EngineBrake",
                    "type": "Number"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": []
        }
    ]
}

```

### Affected Product Version:

iotagent-node-lib latest

### Environment details (with versions):

OS: Windowd 10
Env (Docker/K8s): Docker
Application: iotagent-opcua

**Comment by mapedraza** [comment]
Researching about this issue:

In this part of the code:
https://github.com/telefonicaid/iotagent-node-lib/blob/38ba03bf04c1e38687048eb8dbc2bd0137bc82c8/lib/services/northBound/deviceProvisioningServer.js#L150-L170

The IoTA calls to `checkMandatoryQueryParams()` passing an array of mandatory params in the body (`['device_id']`) and each single device of the request. 

Reviewing `checkMandatoryQueryParams()`
https://github.com/telefonicaid/iotagent-node-lib/blob/38ba03bf04c1e38687048eb8dbc2bd0137bc82c8/lib/services/northBound/restUtils.js#L44-L77

We can see it is only checking if the key exists, but not the value. 

Since `checkMandatoryQueryParams` [is not used in other part in the codebase](https://github.com/telefonicaid/iotagent-node-lib/search?q=%27checkMandatoryQueryParams%27), a simple approach could be to check if not empty or null inside `checkMandatoryQueryParams()` function in case of match

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1300

**Comment by fgalan** [comment]
@manfredipist could you confirm it is now fixed? You would probably need to donwload again `:latest` IOTA from `telefonicaiot` dockerhub organization.

**Comment by manfredipist** [comment]
I confirm it has been fixed, thanks!
