### ISSUE TITLE
Error PayloadTooLarge

### ISSUE THREAD

**Issue by MichelSc** [telefonicaid/iotagent-node-lib#1307]
I need to receive a notification larger than 100kb.

When a receiving the notification, an error PayloadTooLarge is thrown by the bodyparser in the northboundserver and the notification is not handled: NOK.

This issue requires to implement a limit configuration parameter, that will be passed to the northboundserver at start time.

Instead of hardcoding the limit as follows
```
    northboundServer.app.use(bodyParser.json({ limit: '50mb'}));
    northboundServer.app.use(bodyParser.json({ type: 'application/*+json' , limit: '50mb'}));
```

Or any other solution working around the limit of 100kb of the bodyparser json parser.

**Comment by mapedraza** [comment]
As I can see, the limits you pasted are 50mb, much bigger than the 100kb of your notification, it is right?

**Comment by MichelSc** [comment]
The 100kb is the hard-coded limit I need to get rid of (default from bodyparser).

My notification is around 1.8mb big.

In my example, I raise the limit to 50mb, so comfortably higher than my notification.

**Comment by fgalan** [comment]
Could you provide more detail on your use case, please?

In particular, why do you need so large payload? Typically, the measures that IoTA process are much smaller than that.

**Comment by MichelSc** [comment]
Devices from the edge send raw data as json objects to Orion Context Broker. These raw data are vibrations (accelerations) with a frequency of 50KHz and sent as blobs with a frequency of 1Hz. Each blob contains 50K accelerations and is 1.8MB
When a new blob arrive, I need to be notified, and to process the blob.

**Comment by mapedraza** [comment]
Probably is a good idea to include it as [configuration parameter](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md) into the agent. Since you already identified how to change that parameter, are you whiling to contribute to enable it as [configuration parameter](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md)?

This file contains all the configuration parameters:
https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/commonConfig.js

If you need more help, please let us know
Best regards

**Comment by MichelSc** [comment]
After weighted reflection, we decided not to rely on iotagent-node-lib to solve our connection need.

@mapedraza: this issue is for your information; we will not fix it.
