### ISSUE TITLE
remove depecated features:  appendMode  and bidirecciontal plugin (for 3.3.0+)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1413]
### Component

Techdeb

**Comment by AlvaroVega** [comment]
The following code will be removed: 

https://github.com/telefonicaid/iotagent-node-lib/blob/4d7c824505a527ff76e4474d5d508d6e5445c19b/lib/services/devices/devices-NGSI-v2.js#L73-L102

https://github.com/telefonicaid/iotagent-node-lib/blob/4d7c824505a527ff76e4474d5d508d6e5445c19b/lib/services/devices/devices-NGSI-v2.js#L202-L258

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/iotagent-node-lib/pull/1416

**Comment by AlvaroVega** [comment]
related with works done in https://github.com/telefonicaid/iotagent-node-lib/pull/1390

**Comment by mapedraza** [comment]
@jason-fox there are some changes applied recently to IoTA that also affects to NGSI-LD side

For your information, as you can see from the issue title, we are going to remove bidirectional attributes in next release (3.4.0) in order to remove legacy code related with plugins architecture. In the future, subscription based commands will be added in a proper way. 

For that reason, I think it is important to validate all the NGSI-LD functionality at 3.3.0

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1421
