### ISSUE TITLE
About the unique range of Device ID

### ISSUE THREAD

**Issue by hiro-noguchi** [telefonicaid/iotagent-node-lib#666]
Hi, FIWARE experts.
I am testing FIWARE including IoT Agent(iotagentjson)

# Expected Behavior

Since Device IDs need only be unique within the same API Key, if the Entity Type is different for the same Fiware-Service and Fiware-ServicePath, the same Device ID should be available.

That is, if you create devices belonging to different Service Resources, you should be able to use the same Device ID.

# Current Behavior

When creating devices with the same Fiware-Service, same Fiware-ServicePath, different Entity Type, same Device ID, the following error occurs.

- error

`
{“name”: “DUPLICATE_DEVICE_ID”, “message”: “A device with the same pair (Service, DeviceId) was found: device-01”}
`

The setting contents are as follows.

| Parameters | TemperatureSensor01 |  HumiditySensor01 |
|:-:|:-:|:-:|
| Fiware-Service | user01 |  user01 |
| Fiware-ServicePath | / | / |
| Resource | "" | "" |
| API Key | apikey01 | apikey02 |
| Entity Type | TempSensor | HumiSensor |
| Device ID | device-01 | device-01 |
| Entity Name | TempSensor:device-01 |  HumiSensor:device-01 |`

- Create Service Resource

`
curl -iX POST 'http://localhost:4041/iot/services' -H 'Content-Type: application/json' -H 'fiware-service: user01' -H 'fiware-servicepath: /' -d '{"services":[{"apikey":"apikey01","entity_type":"TempSensor","resource":""}]}'
`

`
curl -iX POST 'http://localhost:4041/iot/services' -H 'Content-Type: application/json' -H 'fiware-service: user01' -H 'fiware-servicepath: /*' -d '{"services":[{"apikey":"apikey02","entity_type":"HumiSensor","resource":""}]}'
`

- Create Device Resource

`
curl -sX POST 'http://localhost:4041/iot/devices' -H "Fiware-Service: user01" -H "Fiware-ServicePath: /" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{"devices": [{"device_id": "device-01"," entity_name":"TempSensor:device-01","entity_type": "TempSensor","attributes": [{"object_id":"t","name":"temperature","type": "number"}],"transport": "MQTT"}]}'
`

`
curl -sX POST 'http://localhost:4041/iot/devices' -H "Fiware-Service: user01" -H "Fiware-ServicePath: /" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{"devices": [{"device_id": "device-01"," entity_name":"HumiSensor:device-01","entity_type": "HumiSensor","attributes": [{"object_id":"h","name":"humidity","type": "number"}],"transport": "MQTT"}]}'
`

# Possible Solution

Currently it seems to be confirmed whether the combination of Device ID, Fiware-Service and Fiware-ServicePath is unique.

`https://github.com/telefonicaid/iotagent-node-lib/blob/fb1c50b6060ad9a7829713c115b497ed1cd73662/lib/services/devices/deviceService.js#L576`

I think that I need to be confirmed  whether combination of Device ID, Fiware-Service, Fiware-ServicePath and Entity Type is unique.

# Your Environment

IoT Agent(iotagentjson)Version : libVersion":"2.6.0","version":"1.7.0"
Orion Version : "1.14.0"

**Comment by fgalan** [comment]
@hiro-noguchi I have seen the issues was close. Did you finally find a solution for it?

**Comment by hiro-noguchi** [comment]
No I didn't
I thought that should be to written in the issue of iotagent-json, not iotagent-node-lib.

**Comment by fgalan** [comment]
I think is a general behaviour of all the agent. Thut, probably is right in this repo, so I'd suggest to reopen the issue, pls.

**Comment by fgalan** [comment]
Let me clarify how IOTAgents unicity is suposed to work, please.

In general, our criteria to define unicity along all components in the plataform which are compliant with the service & subservice multitenancy system is that the following tuple define unicity:

```
<serv, subserv, resource_id>
```

In the case of IOTAs resource_id is the device_id, so we have:

```
<serv, subserv, dev_id>
```

Note the entity type used in IOTA device provisioning is not part of the resource id. I mean, it is not part of the identification of the device, but a parameter of the device (in particular, a parameter to map information to an entity in a CB). As far as I understand by your report, that's the behaviour your are observing.

Note that the `<serv, subserv, resource_id>` solution is different in the case of CB. In the case of CB resource_id is defined by entity_id plus entity_type. So that results in:   `<serv, subserv, entity_id, entity_type>` in that case. The situation is different from IOTAs, and maybe this has caused some confussion :)

**Comment by fgalan** [comment]
After a couple of week after last comment, I understand the doubt/question in this issue gets addressed, so I'm going to close. Please @hiro-noguchi reopen it if I'm wrong and we keep discussing. Thx!
