### ISSUE TITLE
ngsi v2 configuration

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-node-lib#791]
looking at the iot agent lib, it seems that configuration should specify the protocol used as follow:
```
        contextBroker: {
            host: '192.168.1.1',
            port: '1026',
            ngsiVersion: 'v2'
        }
```

This is not documented in any agent neither in the lib, afaik.

**Comment by dcalvoalonso** [comment]
I have just created a PR with this small update in the docs: https://github.com/telefonicaid/iotagent-node-lib/pull/792

Please feel free to add comments to improve the documentation! ;)

**Comment by chicco785** [comment]
@dcalvoalonso @fgalan shouldn't be this also available in the `config.js`of the iot agents? e.g. https://github.com/telefonicaid/iotagent-json/blob/master/config.js ?

**Comment by fgalan** [comment]
> @dcalvoalonso @fgalan shouldn't be this also available in the config.jsof the iot agents? e.g. https://github.com/telefonicaid/iotagent-json/blob/master/config.js ?

We should avoid duplicating documentation. Configuration related to the common functionality (such as the northbound) should be included in the library and a proper link should be added from IOTAs documentation to library documentation (maybe that link already exists?). Configuration specific to the IOTA (mainly documentation related to the southbound transport mechanism supported by the agent) should be included in the IOTA documentation.

Duplicating the same configuration in several places is, in general, a bad ideal. It gets desynchronized very often and it is difficult and costly to keep it synced. For instance, instead of one fixing PR such as the #792 done by @dcalvoalonso we would need to do at least 5 fixing PRs (IOTA Node Lib + IOTA UL + IOTA JSON + IOTA Sigfox + IOTA LMWM... and probably more ones)!

**Comment by chicco785** [comment]
i would anyhow improve the links from agents to lib docs, i think it may be of help :) will try a PR for UL as example.

**Comment by fgalan** [comment]
> i would anyhow improve the links from agents to lib docs, i think it may be of help :) will try a PR for UL as example.

Thanks! PRs improving documentation are always welcome :)
